#!/bin/bash
# Creates an action log with timestamp
# by Evan Teitelman <teitelmanevan@gmail.com>

file=${1:-act.log}

while : ; do
	item=$(vipe < /dev/null)
	echo "$(date +%H:%M:%S) $item" >> "$file"
	#sleep 1
	read
done
