#!/bin/bash
# TODO: screen flasher
# TODO: beep
# TODO: args

pdate=$1
vol=$2

date=$(date +%s "-d$pdate")
now=$(date +%s)
diff=$(( date - now ))

sleep $diff

while sudo ibeep "$vol" ; do
	sleep 1
done
