#!/bin/bash

needs root || exit $?

# Select interface
if [[ $1 ]] ; then
	interface="$1"
else
	interface=eth0
fi

# arp-scan's output is a bit annoying to parse
arp-scan -lqg -I "$interface" |
cut -d$'\t' -f1 |
sed '1,2d' |
sed '/^$/,$d'
