#!/bin/sh
# Call calibre with a session-only database
# by Evan Teitelman <teitelmanevan@gmail.com>

tmp=$(mktemp -d)
trap "rm -rf '$tmp'" EXIT

calibredb add "--library-path=$tmp" "$@"
calibre "--with-library=$tmp"
