#!/bin/bash

usage() {
	cat <<EOF
$(basename "$0") [-h] [-d|-x|-a|-b]
EOF
}

if [[ $# = 0 ]] ; then
	usage
	exit
fi

input=ascii
args=("$@")

case "$1" in
	-d)
		input=dec
		shift 1
		;;
	-x)
		input=hex
		shift 1
		;;
	-a)
		input=ascii
		shift 1
		;;
	-b)
		input=binary
		shift 1
		;;
	*)
		;;
esac

case $input in
	dec) ;;
	hex) echo -n "$@" | xxd -ps -r ;;
	ascii) echo -n "$@" | xxd -c1 ;;
	#binary) echo -n "$@" | 
esac
