#!/bin/bash

if [[ $# != 0 ]] ; then
	dir="$1"
	cd "$dir"
fi

rm -f *.class *.o *.bin
rm -f *.swp *.swo *~

for tex_file in *.tex ; do
	base=${tex_file/.tex/}
	for ext in aux log dvi pdf idx out nav snm toc ; do
		rm -f "$base.$ext"
	done
done
