#!/bin/bash

if (( $# >= 1 )) ; then
	dir="$1"
	cd "$dir"
fi

rm -f *.class *.o *.bin
rm -f *.swp *.swo *~

for tex_file in *.tex
do
	base=${tex_file/.tex/}
	for ext in aux log dvi pdf idx out nav snm toc
	do
		file="$base.$ext"
		rm -f "$file"
	done
done
