#!/bin/bash
# Manipulates the line ordering of data passed to stdin by the specified columns
#  with a specified command and prints the results to stdout.

usage() {
	cat <<EOF
Usage: $(basename "$0") [-d<delim>] -- command
EOF
}

delim=$'\t'
cmd=()
cols=()

command_time=false

for arg ; do
	case "$arg" in
		-d?)
			# Delimiter must be attached to its flag
			delim=${arg:2}
			;;
		--)
			command_time=true
			;;
		*)
			if $command_time ; then
				cmd+=("$arg")
			else
				cols+=("$arg")
			fi
			;;
	esac
done

number_lines() {
	local input=$(cat)
	input_len=$(echo "$input" | wc -l | cut -d' ' -f1)
	echo "$input" | paste <(seq 1 $input_len) -
}

if [[ ${#cols[@]} = 0 ]] ; then
	echo >&2 "No columns specified."
	usage
	exit 1
fi

if [[ ${#cmd[@]} = 0 ]] ; then
	echo >&2 "No command specified."
	usage
	exit 1
fi

input=$(cat)

# The line numbers are used to correlate the output lines with their dragging text
echo "$input" | cut -d "$delim" -f $(echo ${cols[@]} | tr ' ' ',')  |
number_lines | eval "${cmd[@]}" |
cut -d$'\t' -f1 |
while read line ; do
	echo "$input" | sed -n "${line}p"
done
