#!/bin/bash
# Useful for quickly transferring data off of encrypted flashdrives.

if [[ $# == 1 ]] ; then
	cryptsetup open --type=tcrypt "$1" dat
	mount /dev/mapper/dat /dat
else
	umount /dev/mapper/dat
	cryptsetup close dat
fi
