#!/bin/bash
# Useful for quickly transferring data off of encrypted flashdrives.

name=${2:-dat}

if [[ $1 == close ]] ; then
	umount "/dev/mapper/$name"
	cryptsetup close "$name"
else
	mkdir -p "/$name"
	cryptsetup open --type=tcrypt "$1" "$name"
	mount "/dev/mapper/$name" "/$name"
fi
