#!/bin/bash
# cryptsetup wrapper
# Useful for quickly transferring data off of encrypted flashdrives.
# by Evan Teitelman <teitelmanevan@gmail.com>

# TODO: add -flags
dev=${1:-/dev/sdc1}
name=${2:-dat}
dir=/$name
mapper=/dev/mapper/$name
mnt_opts=$3

needs root || exit 1

if [[ $dev == close ]] ; then
	umount "$mapper"
	cryptsetup close "$name"
	rmdir "$dir"
else
	mkdir -p "$dir"
	cryptsetup open --type=tcrypt "$dev" "$name"
	mount -o "$mnt_opts" "$mapper" "$dir"
fi
