#!/bin/bash

dev=sdc1
fs=true
mount_dir=/dump/$RANDOM
mkdir -p $mount_dir

if [[ $# != 0 ]] ; then
	if [[ $(basename $dev) = mem ]] ; then
		fs=false
	fi
	dev=$1
	if [[ $# != 1 ]] ; then
		fs=$2
	fi
fi

if [[ "$(dirname $dev)" = . ]] ; then
	dev=/dev/$dev
fi

if [[ ! -r $dev ]] ; then
	echo 2>&1 "Unable to read from the device."
	exit 1
fi

# TODO: change the date format
dump_dir="dump/$(basename $dev)-$(date +'%T')"
mkdir -p "$dump_dir" || exit 1

if $fs ; then
	echo "FS..."
	if mount -o ro,noexec $dev $mount_dir ; then
		rsync -az ${mount_dir}/ "$dump_dir"
		umount $dev
	fi
fi

echo "I..."
dd if=$dev of="$dump_dir/dev.img"
