#!/usr/bin/perl
# Extract email addresses
# by Evan Teitelman <teitelmanevan@gmail.com>

while (<>) {
	my @matches = /([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+)/g;
	for my $match (@matches) {
		printf "%s\n", $match 
	}
}
