#!/bin/sh
# encfs wrapper
# by Evan Teitelman <teitelmanevan@gmail.com>

rel=$1
shift
abs=$(grealpath "$rel")
enc=$(gdirname "$abs")/.$(gbasename $rel)

gmountpoint -q "$abs" || encfs "$enc" "$abs" "$@"
