#!/bin/sh
# Extract various archives
# by Evan Teitelman <teitelmanevan@gmail.com>

err() {
	echo >&2 "$*"
}

die() {
	err "$*"
	exit 1
}

ndirs() {
	dir=$1
	set -- "$dir"/*
	echo $#
}

shift_dirs() {
	dir=$1
	subdir=$(find "$dir" -maxdepth 1 -type d)
	while [ $(ndirs) ; do

	done
}

[ $# = 0 ] && die "No file specified."
[ -f "$1" ] || die "'$1' does not exist."

tmp=$(mktemp -d)
trap 'rm -rf $tmp' EXIT

for arg ; do
	mkdir -p "$tmp/$arg.d"
	cp "$arg" "$tmp/$arg.d"
	(
	cd "$tmp/$arg.d"
	case "$arg" in
		*.tar.bz2)      tar xvjf "$arg"   ;;
		*.tar.xz)       tar xvJf "$arg"   ;;
		*.tar.gz|*.tgz) tar xvzf "$arg"   ;;
		*.bz2)          bunzip2 "$arg"    ;;
		*.rar)          unrar x "$arg"    ;;
		*.gz)           gunzip "$arg"     ;;
		*.tar)          tar xvf "$arg"    ;;
		*.tbz2)         tar xvjf "$arg"   ;;
		*.zip)          unzip "$arg"      ;;
		*.Z)            uncompress "$arg" ;;
		*.7z)           7z x "$arg"       ;;
		*.a)            ar x "$arg"       ;;
		*)              err "Unable to extract '$arg'." ;;
	esac
	)
	shift_dirs "$tmp/$arg.d"
done
# vim: set ft=zsh:
