#!/bin/bash

# Check for no delete flag
if [[ $1 == "-n" || $1 == "--no-delete" ]]; then
	delete_mode=""
else
	delete_mode="--delete-after"
fi

# Directories
remote="locserv:"
dirs="/home/evan/desk/ro /home/evan/media /home/evan/ela /home/evan/erep"

# Backup each directory
for dir in $dirs ; do
	echo "Backing up $(basename ""$dir"")."
	remote_dir=$dir
	rsync -avzy --progress $delete_mode -e "ssh" "$dir/" "$remote$remote_dir"
done
