#!/bin/bash
# Retrieves packages in a list file from a mirror
# It's a bit brute, but it works
# by Evan Teitelman <teitelmanevan@gmail.com>

url="http://us.mirror.archlinuxarm.org/arm"
repos="core extra community"
types="any arm"
extension="pkg.tar.xz"

if [[ $# = 0 ]] ; then
	echo "No file specified. Reading from stdin." >&2
	list_file=/dev/stdin
else
	list_file="$1"
fi

while read package ; do
	for repo in $repos ; do
		for type in $types ; do
			location=$url/$repo/$package-$type.$extension
			echo $location
			wget "$location" && error=0 && break
			error=1
		done

		if [[ $error != 0 ]] ; then
			echo "'$package' not found in $repo." >&2
		else
			echo "'$package found in $repo."
			break
		fi
	done
done < "$list_file"

exit $error
