#!/bin/bash

# Make sure there are arguments
if (( $# == 0 )); then
	exit 1
fi

# Check for repository root
if [[ ! -d .git ]]; then
	echo "$0: this script must be run at the root of a repository."
	exit 1
fi

# Filter history
git filter-branch --force --index-filter "git rm -rf --cached --ignore-unmatch ""$@""" --prune-empty -- --all

# Remove old objects and refs
rm -rf .git/refs/original/ && git reflog expire --all && git gc --aggressive --prune
