#!/bin/bash
# Modify remote URLs in bulk
# by Evan Teitelman <teitelmanevan@gmail.com>

usage() {
	cat >&2 <<USAGE
usage: $(basename "$0") [-h] PATTERN REMOTE...
USAGE
}

if (( $# < 2 )) || [[ $1 = -h ]] ; then
	usage
	exit 1
fi

pattern="$1"

for remote in ${@:2} ; do
	old_url=$(git remote -v |
	grep "^$remote\s" |
	cut -d$'\t' -f2 |
	cut -d' ' -f1 |
	sort -u)

	new_url=$(echo "$old_url" | sed "$pattern")
	git remote set-url $remote "$new_url"
	echo -n "'$old_url' -> '$new_url'"
	if [[ "$old_url" = "$new_url" ]] ; then
		echo " (no change)"
	else
		echo
	fi
done
