#!/bin/bash

if (( $# == 0 )); then
	exit 1
fi

if [[ ! -d .git ]]; then
	echo "$0: this script must be run at the root of a repository."
	exit 1
fi

files=$@
git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch $files" HEAD

rm -rf .git/refs/original/ && git reflog expire --all && git gc --aggressive --prune
