#!/bin/bash
# Get a gitignore file
# by Evan Teitelman <teitelmanevan@gmail.com>

basedir=$HOME/ecod/gitignore

for gitignore ; do
	files=("$basedir/$gitignore.gitignore"
	       "$basedir/Global/$gitignore.gitignore")

	cat "$(printf '%s\n' "${files[@]}" | head -n1)"
done
