#!/bin/bash
# Wrapper to use the Garmin Colorado with gpsd.
# by Evan Teitelman <teitelmanevan@gmail.com>

cleanup() {
	rm -f "$temp"
	kill $!
}
trap cleanup EXIT

set -e

needs garminusb2nmea gpsd || exit $?

dev=${1:-/dev/ttyUSB0}

temp=test
mkfifo "$temp"

garminusb2nmea "$dev" "$temp" &
gpsd -D6 -Nn "$temp"
