#!/bin/bash
# This is a wrapper to use the Garmin Colorado with gpsd.

cleanup() {
	rm -f "$temp"
	kill $!
}
trap cleanup EXIT

set -e

if . "${UTILS_SHARED:-.}/common.sh" ; then
	needs garminusb2nmea gpsd
fi

dev=${1:-/dev/ttyUSB0}

temp=test
mkfifo "$temp"

garminusb2nmea "$dev" "$temp" &
gpsd -D6 -Nn "$temp"
