#!/usr/bin/env python
import sys
import matplotlib.pyplot as plt
import string

infs = []
if len(sys.argv) == 1:
	infs.append(sys.stdin)
else:
	infs.extend([open(arg, 'r') for arg in sys.argv[1:]])

classes = []
# go through each input
for inf in infs:
	cls = {'class': inf.name, 'grades': []}
	# go through the input lines
	for line in inf:
		parts = line.split('\t')
		# split scores
		score = parts.pop(2)
		if '/' in score:
			parts.extend(score.split('/'))
		else:
			parts.extend([score[:-1], '100'])
		# strip whitespace
		parts = [part.strip() for part in parts]
		cls['grades'].append(dict(zip(['name', 'type', 'date', 'score', 'possible'], parts)))
	classes.append(cls)

total=0.0
possible=0.0
for cls in classes:
	scores = []
	for grade in cls['grades']:
		total += float(grade['score'])
		possible += float(grade['possible'])
		score = total / possible * 100
		scores.append(score)
	#plt.clf()
	#plt.plot(scores)
	#plt.show()
	print("Grade: " + str(total / possible * 100))
