#!/bin/bash
# Network config
# TODO: merge in wpa_sup stuff
# TODO: improve args
# by Evan Teitelman <teitelmanevan@gmail.com>

set -e

if=${1:-eth0}

randomize_mac=false
wifi_creds=/home/para/pass/wifi

tmp=$(mktemp -d /tmp/net.XXXXXX)

setup_vpn() {
	cat > "$tmp/ca.crt" <<EOF
-----BEGIN CERTIFICATE-----
MIID2jCCA0OgAwIBAgIJAOtqMkR2JSXrMA0GCSqGSIb3DQEBBQUAMIGlMQswCQYD
VQQGEwJVUzELMAkGA1UECBMCT0gxETAPBgNVBAcTCENvbHVtYnVzMSAwHgYDVQQK
ExdQcml2YXRlIEludGVybmV0IEFjY2VzczEjMCEGA1UEAxMaUHJpdmF0ZSBJbnRl
cm5ldCBBY2Nlc3MgQ0ExLzAtBgkqhkiG9w0BCQEWIHNlY3VyZUBwcml2YXRlaW50
ZXJuZXRhY2Nlc3MuY29tMB4XDTEwMDgyMTE4MjU1NFoXDTIwMDgxODE4MjU1NFow
gaUxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJPSDERMA8GA1UEBxMIQ29sdW1idXMx
IDAeBgNVBAoTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMSMwIQYDVQQDExpQcml2
YXRlIEludGVybmV0IEFjY2VzcyBDQTEvMC0GCSqGSIb3DQEJARYgc2VjdXJlQHBy
aXZhdGVpbnRlcm5ldGFjY2Vzcy5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJ
AoGBAOlVlkHcxfN5HAswpryG7AN9CvcvVzcXvSEo91qAl/IE8H0knKZkIAhe/z3m
hz0t91dBHh5yfqwrXlGiyilplVB9tfZohvcikGF3G6FFC9j40GKP0/d22JfR2vJt
4/5JKRBlQc9wllswHZGmPVidQbU0YgoZl00bAySvkX/u1005AgMBAAGjggEOMIIB
CjAdBgNVHQ4EFgQUl8qwY2t+GN0pa/wfq+YODsxgVQkwgdoGA1UdIwSB0jCBz4AU
l8qwY2t+GN0pa/wfq+YODsxgVQmhgaukgagwgaUxCzAJBgNVBAYTAlVTMQswCQYD
VQQIEwJPSDERMA8GA1UEBxMIQ29sdW1idXMxIDAeBgNVBAoTF1ByaXZhdGUgSW50
ZXJuZXQgQWNjZXNzMSMwIQYDVQQDExpQcml2YXRlIEludGVybmV0IEFjY2VzcyBD
QTEvMC0GCSqGSIb3DQEJARYgc2VjdXJlQHByaXZhdGVpbnRlcm5ldGFjY2Vzcy5j
b22CCQDrajJEdiUl6zAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAByH
atXgZzjFO6qctQWwV31P4qLelZzYndoZ7olY8ANPxl7jlP3YmbE1RzSnWtID9Gge
fsKHi1jAS9tNP2E+DCZiWcM/5Y7/XKS/6KvrPQT90nM5klK9LfNvS+kFabMmMBe2
llQlzAzFiIfabACTQn84QLeLOActKhK8hFJy2Gy6
-----END CERTIFICATE-----
EOF

	cat > "$tmp/crl.pem" <<EOF
-----BEGIN X509 CRL-----
MIIBgTCB6zANBgkqhkiG9w0BAQ0FADCBpTELMAkGA1UEBhMCVVMxCzAJBgNVBAgT
Ak9IMREwDwYDVQQHEwhDb2x1bWJ1czEgMB4GA1UEChMXUHJpdmF0ZSBJbnRlcm5l
dCBBY2Nlc3MxIzAhBgNVBAMTGlByaXZhdGUgSW50ZXJuZXQgQWNjZXNzIENBMS8w
LQYJKoZIhvcNAQkBFiBzZWN1cmVAcHJpdmF0ZWludGVybmV0YWNjZXNzLmNvbRcN
MTQwNTA3MTgwOTE5WhcNMjQwNTA3MTgwOTE5WjAUMBICAQEXDTE0MDQyODIyMDMy
NVowDQYJKoZIhvcNAQENBQADgYEA4EA2wjio+BxYFui1mBj5gmypxUQyA7xQJ3Vo
cwWSllQKHpfmQ7fwyTL22uc21W9hM4geD1FwoXDUEraQjfyBJOxJwc6GOhTN2wHv
3vplKjdbXmxxAfjduBvlIB0a6qSz1L6hwZJrZUGimlWS9NQrmYaKLbtG07n2UyA+
mqz5bEc=
-----END X509 CRL-----
EOF

	passr privateinternetaccess -p | cut -d' ' -f2- | tr ' ' '\n' > "$tmp/login.conf"
	host=108.170.8.202
	#sudo ip r a $host via $gw dev $if ||:

	cat > "$tmp/openvpn.conf" <<EOF
client
dev tun
proto tcp
# (sweden)
remote $host 443
resolv-retry infinite
nobind
persist-key
persist-tun
ca $tmp/ca.crt
tls-client
remote-cert-tls server
auth-user-pass $tmp/login.conf
comp-lzo
verb 1
reneg-sec 0
crl-verify $tmp/crl.pem
EOF

	sudo openvpn "$tmp/openvpn.conf"
}

blackhole_route() {
	echo 'adding blackhole route...'
	sudo ip r a default via 127.0.0.1 dev lo metric 0 ||:
}

random_mac() {
	local if=$1
	sudo macchanger -r "$if"
}

setup_eth() {
	local if=$1

	echo 'killing dhcpcd'
	sudo killall dhcpcd 2> /dev/null || true
	while pgrep dhcpcd ; do sleep 1 ; done

	echo 'starting dhcpcd'
	dhcps $if
	# TODO really dangerous race condition here... fix it!

	# get gateway
	gw=$(arp -an | awk '{ print $2 }' | tr -d '()' | head -n1)
	gw_mac=$(arp -an | awk '{ print $4 }' | tr -d '()' | head -n1)

	echo 'cleaning default routes'
	#while sudo ip r d default dev $if 2> /dev/null; do sleep 1; done
	#while sudo ip r d default dev lo 2> /dev/null; do sleep 1; done

	echo "$if gateway: $gw $gw_mac"
}

setup_wifi() {
	local if=$1
	local id=$2

	. "$wifi_creds"

	if ! declare -f wifi_$if &> /dev/null ; then
		die "unknown network: $id"
	fi
	wifi_$id
}

clean_default_routes() {
	ip r | grep '^default ' |
	xargs -n1
	while read route ; do
		ip r d $route
	done
}

static_arp() {
	sudo arp -s $gw $gw_mac
}

if $randomize_mac ; then
	random_mac "$if"
fi

case "$if" in
	eth*)
		setup_eth "$if"
		;;
	wlan*)
		setup_wifi "$if"
		;;
	vpn)
		setup_vpn
		;;
esac
