#!/bin/bash
# A light wrapper around irssi to handle configuration.

tmp=$(mktemp /tmp/irssi.XXXXXX)
trap "rm $tmp" EXIT

cat "$HOME/.irssi/config" > "$tmp"

# I don't care enough about IRC passwords to encrypt this file.
i=0
while grep -q "pass$i=" "$HOME/.irssi/pass" ; do
	pass=$(grep "pass$i=" "$HOME/.irssi/pass" | cut -d= -f2)
	sed -i "s/PASS$i/$pass/g" "$tmp"
	(( i++ ))
done

while grep -q 'REALNAME' "$tmp" ; do
	sed -i "0,/REALNAME/s/FULLNAME/$(makepasswd)/g" "$tmp"
done

while grep -q 'USERNAME' "$tmp" ; do
	sed -i "0,/USERNAME/s/FULLNAME/$(makepasswd)/g" "$tmp"
done

irssi --config=$tmp
