#!/bin/bash
# A light wrapper around irssi to handle configuration.

tmp=$(mktemp /tmp/irssi.XXXXXX)
trap "rm $tmp" EXIT

cat "$HOME/.irssi/config" > "$tmp"

while grep -q '%RANDOM%' "$tmp" ; do
	sed -i "0,/%RANDOM%/s/%RANDOM%/$(makepasswd --chars 8 --string 'abcdefghijklmnopqrstuvwxyz')/g" "$tmp"
done

irssi --config=$tmp
