#!/bin/bash
# Turn text into LaTeX
# TODO handle quotation marks and such
# by Evan Teitelman <teitelmanevan@gmail.com>

# Print the beginning of the document
echo '\documentclass{article}'
echo '\begin{document}'

if [[ $1 != "-t" ]] ; then
	cat
fi

# Print the ending of the document
echo '\end{document}'
