#!/bin/bash

# Print the beginning of the document
echo '\documentclass{article}'
echo '\begin{document}'

if [[ $1 != "-t" ]] ; then
	# Read text from stdin and print it with no modifications
	while read line ; do
		echo $line
	done
fi

# Print the ending of the document
echo '\end{document}'
