#!/bin/bash

root="$HOME"
sec_dir="${2:-sec}"
sec_tar=".${sec_dir}.tar.gz"
sec_asc="${sec_tar}.asc"

# force gpg to use the ncurses pinentry
unset DISPLAY

cd ${root}

if [[ $1 == "e" ]] ; then
	tar -czf ${sec_tar} ${sec_dir} &&
		gpg -ea -r evan ${sec_tar} &&
		srm ${sec_tar}
	echo
elif [[ $1 == "d" ]] ; then
	gpg ${sec_asc} &&
		tar -xzf ${sec_tar} &&
		srm ${sec_tar}
	echo
elif [[ $1 == "c" ]] ; then
	echo "Removing ${sec_dir}/..."
	srm -rf ${sec_dir}
	echo "Removing ${sec_tar}..."
	srm ${sec_tar}
	echo
elif [[ $1 == "l" ]] ; then
	gpg ${sec_asc} &&
		tar -tzf ${sec_tar} &&
		srm ${sec_tar}
	echo
fi

[[ -d ${sec_dir} ]] && echo "Warning: unencrypted data at ${sec_dir}/ exists."
[[ -f ${sec_tar} ]] && echo "Warning: unencrypted data at ${sec_tar}/ exists."
[[ -f ${sec_asc} ]] && echo "Info: ${sec_asc} exists."
