#!/bin/sh
# Ping with musical sounds
# by somebody else (not sure whom)

ping "$@" |
awk -F[=\ ] '/me=/{ t=$(NF - 1); f = 3000 - 14 * log(t ^ 20); c="play -q -n synth 1 pl " f; print $0; system(c) }'
