#!/usr/bin/env perl
# Mutate characters
# usage: mutchar <str> <expr>
# example: $ mutchar abcd +5
#          fghi
# by Evan Teitelman <teitelmanevan@gmail.com>

use strict;

my $str = $ARGV[0];
my $expr = $ARGV[1];

my @chars = split //, $str;
for (@chars) {
	eval "\$_ = chr(ord(\$_) $expr)";
}

printf "%s\n", join '', @chars;
