#!/bin/sh
# For script dependencies
# by Evan Teitelman <teitelmanevan@gmail.com>

die() {
	echo >&2 "$@"
	exit 1
}

while [ -n "$1" ] ; do
	case "$1" in
		-e) extra_error=$2 ;  shift ;;
		root) [ $UID -eq 0 ] || die "Must be root. $extra_error" ;;
		*) command -v "$1" > /dev/null 2>&1 || die "Needs $1. $extra_error" ;;
	esac
	shift
done
