#!/bin/sh
# Add a note to a list
# by Evan Teitelman <teitelmanevan@gmail.com>

list=$1
shift
thing=$*
file=$HOME/notes/$list

if grep -qih "^$thing$" "$file" ; then
	echo 'already in list.'
	exit
fi

if grep -iq "$thing" "$file" ; then
	echo
	grep -ih "$thing" "$file" | nl
	echo
	echo -n 'is it one of these (Yn)? '
	read ans
	case "$ans" in
		n|N) ;;
		*) echo >&2 'not adding.'; exit 1 ;;
	esac
fi

echo >&2 "adding '$thing' to $list list..."
echo "$thing" >> "$file"
