#!/bin/bash

base=${BASH_SOURCE[0]%/*}
package_list=$HOME/cod/blackarch/blackarch-iso/live-iso/packages.para

act=$1

usage() {
	cat <<EOF
manage.sh: ACTION

where ACTION is one of

EOF
}

list_machine_packages() {
	pacman -Qqe | sort
}

list_machine_packages_filtered() {
	comm -32 <(list_machine_packages) \
	         <(pacman -Qgg | grep -E '^(blackarch|base|base-devel) ' |
			   cut -d' ' -f2 | sort -u)
}

list_file_packages() {
	sed '/^#/d' "$package_list" | sort -u
}

list_new() {
	comm -32 <(list_machine_packages_filtered) <(list_file_packages)
}

list_removed() {
	comm -31 <(list_machine_packages_filtered) <(list_file_packages)
}

list_good() {
	comm -21 <(list_machine_packages_filtered) <(list_file_packages)
}

list_dirt() {
	echo 'NEW:'
	list_new
	echo
	echo 'REMOVED:'
	list_removed
}

do_clean_machine() {
	list_new | sudo xargs pacman --noconfirm -Rns
}

do_clean_list() {
	list_removed | while read p ; do
		sed -i "/^$p$/d" "$package_list"
	done
}

case "$act" in
	rmed|removed) list_removed ;;
	new)          list_new ;;
	good)         list_good ;;
	dirt)         list_dirt ;;
	clean)        do_clean_machine ;;
	listclean)    do_clean_list ;;
	*)
		usage
		exit 1
		;;
esac
