#!/bin/bash

needs sponge

dir=$HOME/pass
enc "$dir" || exit 1
cd "$dir"
file=pass

read_pass() {
	# This is probably pretty leaky... oh well.
	read -sp 'password: ' pass
	echo
	read -sp 'confirm password: ' pass2
	echo
	if [[ "$pass" != "$pass2" ]] ; then
		echo >&2 'passwords do not match'
	fi
}

entry_exists() {
	grep -q "^$1 " "$file"
}

# File format:
#   name username password comment
# Passwords with spaces and null characters are unsupported.
case "$1" in
	a*)
		name=$2
		user=$3
		comment=$4

		if entry_exists "$name" ; then
			echo >&2 "already exists: $name"
			exit 1
		fi

		read_pass

		echo "$name $user $pass $comment" >> "$file"
		;;
	c*)
		name=$2
		if ! entry_exists "$2" ; then
			echo >&2 "entry does not exist: $name"
		fi

		read_pass

		grep "^$name " "$file" | (
			read _ user _ comment

			[[ -n "$3" ]] && username=$3
			[[ -n "$4" ]] && comment=$4

			grep -v "^$name " "$file" | sponge "$file"
			echo "$name $user $pass $comment" >> "$file"
		)
		;;
	d*)
		grep -v "^$2 " "$file" | sponge "$file"
		;;
	l*)
		cut -d' ' -f1 "$file"
		;;
	s*)
		shift
		grep "^$*" "$file"
		;;
	r*)
		if ! entry_exists "$2" ; then
			echo >&2 "entry does not exist: $2"
		fi
		grep "^$2 " "$file"
		;;
	*)
		echo >&2 "unsupported: $1"
		exit 1
		;;
esac
