#!/bin/bash
# Get passwords from a list
# by Evan Teitelman <teitelmanevan@gmail.com>

# override with -c
xselection=primary
# override with -p
print_mode=false
# override with -d
dir=$HOME/pass
# override with -f
file=pass

while (( $# )) ; do
	case "$1" in
		-c) xselection=clipboard ;;
		-p) print_mode=true ;;
		-d) dir=$2; shift ;;
		-f) file=$2; shift ;;
		*)  pattern=$pattern$1 ;;
	esac
	shift
done

if [[ ! -d "$dir" ]] ; then
	echo >&2 "'$dir' does not exist."
	exit 1
fi
if [[ ! -r "$dir/$file" ]] ; then
	echo >&2 "'$dir/$file' not readable."
	exit 1
fi


enc "$dir"
res=$(grep "[^ ]*$pattern" "$dir/$file")
if [[ -z "$res" ]] ; then
	echo >&2 'no results!'
	exit 1
fi
nres=$(wc -l <<< "$res")

if (( $nres > 1 )) ; then
	mapfile -t results <<< "$res"
	echo 'select one:'
	for i in $(seq 1 ${#results[@]}) ; do
		line=${results[$(( i - 1 ))]}
		echo "$i: $(cut -d, -f1 <<< $line ) $(cut -d, -f2 <<< $line)"
	done
	echo -n '> '
	read n
	res=${results[$(( n - 1))]}
fi

service=$(cut -d, -f1 <<< "$res")
user=$(cut -d, -f2 <<< "$res")
pass=$(cut -d, -f3 <<< "$res")
if $print_mode ; then
	echo "$service $user $pass"
else
	echo "service: $service"
	echo "user: $user"
	echo "password copied to $xselection"
	xclip -selection $xselection <<< $pass
fi
