#!/bin/bash
# Get passwords from a list
# by Evan Teitelman <teitelmanevan@gmail.com>

# override with -c
xselection=primary
dir=$HOME/pass

enc "$dir"
pattern=$1
shift
res=$(grep "[^ ]*$pattern" "$dir/pass")
nres=$(wc -l <<< "$res")

for arg ; do
	case "$arg" in
		-c) xselection=clipboard ;;
	esac
done

if (( $nres > 1 )) ; then
	mapfile -t results <<< "$res"
	echo 'select one:'
	for i in $(seq 1 ${#results[@]}) ; do
		line=${results[$(( i - 1 ))]}
		echo "$i: $(cut -d' ' -f1,2 <<< $line )"
	done
	echo -n '> '
	read n
	res=${results[$(( n - 1))]}
elif (( $nres == 1 )) ; then
	echo >&2 'no results!'
	exit 1
fi

user=$(cut -d' ' -f2 <<< "$res")
pass=$(cut -d' ' -f3 <<< "$res")
echo "user: $user"
xclip -selection $xselection <<< $pass
