#!/bin/bash
# Opens some specified ($1) number of pdfs from ~/ela sorted by modification time.
# Opens one pdf by default.

dir="$HOME/ela"
pdf_viewer="zathura"

needs "$pdf_viewer"

num="${1:-1}"

IFS=$'\n'
# TODO: stop using ls
files=($(ls -t ${dir}/*.pdf 2>/dev/null | head -n $num))
if [[ -z "$files" ]] ; then
	echo No pdf files found.
else
	eval $pdf_viewer --fork ${files[@]}
fi
