#!/bin/bash
# Opens some specified ($1) number of pdfs from ~/ela sorted by modification time.
# Opens one pdf by default.

dir=$HOME/ela
pdf_viewer=zathura

num=${1:-1}

while read f ; do
	files+=("$f")
done < <(stat -c $'%Y\t%n' "$dir"/*.pdf 2>/dev/null |
         sort -rn | cut -d$'\t' -f2 |
         head -n $num)

if (( ${#files[@]} == 0 )) ; then
	echo 'No pdf files found.'
else
	eval $pdf_viewer --fork "${files[@]}"
fi
