#!/bin/bash
# Opens some specified ($1) number of pdfs from ~/ela sorted by modification time.
# Opens one pdf by default.

. "${UTILS_SHARED:-.}/common.sh"

dir=$HOME/ela
pdf_viewer=zathura

needs "$pdf_viewer"

num=${1:-1}

files=($(stat -c $'%Y\t%n' "$dir"/*.pdf 2>/dev/null |
         sort -rn | cut -d$'\t' -f2 | head -n $num))
if [[ -z "$files" ]] ; then
	echo 'No pdf files found.'
else
	eval $pdf_viewer --fork "${files[@]}"
fi
