#!/usr/bin/env perl
# Permutate a string in all possible ways
# by Evan Teitelman <teitelmanevan@gmail.com>

use strict;

for (@ARGV) {
	sub perm;
	sub perm {
		my $pre = $_[0];
		my $str = $_[1];
		my $len = length $str;

		if ($len == 0) {
			print "$pre\n";
		} else {
			for my $i (0..$len - 1) {
				perm $pre . (split //, $str)[$i], (substr $str, 0, $i) . (substr $str, $i + 1, $len);
			}
		}
	}
	perm("", $_)
}
