#!/bin/sh
# Poll a site, complain on IRC if it dies
# by Evan Teitelman <teitelmanevan@gmail.com>

wait_success=60
wait_failure=3600
site=blackarch.org
ignore_initial=false

network=irc.genscripts.net
port=6667
#network=localhost
#port=2222
nick=thesiteisbroken
name='Fix It'
channel='#blackarch'
join=false
message="$site is down. Checking again in $wait_failure seconds."
portscan=true
host_info=true

message_delay=2

start_handler() {
	tail -fn0 "$tmp" | nc $network $port &
	trap kill_handler EXIT
}

kill_handler() {
	kill $!
}

write() {
	echo >&2 "$@"
	echo "$@" > "$tmp"
	sleep $message_delay
}

send_alert() {
	write
	write "NICK $nick"
	write "USER $nick 8 * : $name"
	$join && write "JOIN $channel"
	write "PRIVMSG $channel :$message"
	if $portscan ; then
		local sprunge=$(nmap "$site" |& curl -F sprunge=@- sprunge.us)
		write "PRIVMSG $channel :Port scan: $sprunge"
	fi
	if $host_info ; then
		local sprunge=$(host "$site" |& curl -F sprunge=@- sprunge.us)
		write "PRIVMSG $channel :DNS lookup: $sprunge"
	fi
	write "QUIT"
}

tmp=/tmp/irc.$RANDOM$RANDOM
mkfifo "$tmp"
chmod 600 "$tmp"

while true ; do
	if ! curl --connect-timeout 10 "$site" &&
	   ! $ignore_initial &&
	   curl --connect-timeout 10 www.google.com ; then
		echo >&2 failed
		start_handler
		send_alert
		kill_handler
		sleep $wait_failure
	else
		echo >&2 good
		sleep $wait_success
	fi

	ignore_initial=false
done
