#!/bin/sh
# Poll a site
# by Evan Teitelman <teitelmanevan@gmail.com>

site=$1
shift
# The rest of the arguments are the email receipients.

wait_success=60
wait_failure=3600

while true ; do
	if ! curl "$site" > /dev/null ; then
		printf "Subject: $site is down.\n\nChecking site again in $wait_failure seconds." |
		  sendmail "$@"
		sleep $wait_failure
	else
		sleep $wait_success
	fi
done
