#!/bin/bash
# Manages a centralized link system.
#
# Adding links is quick. All you have to do is use 'qln' like so: `qln
# file`. That will create a new link named "file" to $(realpath "file") in
# `qln`'s managed directory ($HOME/ql by default).
#
# If a link named "file" already exists, `qln file` will print the full
# path of the file that the "file" link points to. If the "-f" flag is
# passed to `qln`, all of the links after it will be created regardless
# of whether or not they already exist.

link_dir="$HOME/ql"
force=false

if [[ $# = 0 ]] ; then
	# List links if no arguments
	if [[ ! -d "$link_dir" ]] ; then
		echo "No links."
		exit 1
	fi

	for link in "$link_dir"/* ; do
		echo "$link -> $(realpath "$link")"
	done
	exit
elif [[ $1 = --clear ]] ; then
	# Clear links
	rm -rf "$link_dir"
	echo "All links cleared."
	exit
fi

error=false

# Force link creation
if [[ "$arg" = -f ]] ; then
	force=true
	continue
fi

if [[ $2 ]] ; then
	link="$link_dir/$2"
else
	link="$link_dir/$(basename "$arg")"
fi

if [[ -f "$link" ]] && ! $force ; then
	echo "'$link' already exists."
else
	if [[ -f "$arg" || -d "$arg" ]] ; then
		echo "Creating '$link'"
		mkdir -p "$link_dir"

		ln -fs "$(realpath "$arg")" "$link"
	else
		echo "'$arg' does not exist."
		error=true
	fi
fi

if $error ; then
	exit 1
fi
