#!/bin/bash
# This encapsulates several common nmap scans

# Check for root
if [[ $(whoami) != root ]] ; then
	echo "You probably need to be root to scan."
	#exit 1
fi

# TODO: make these arguments
out='-oG'
scan='-Pn -sS -n --open'
versioning='-sV --version-intensity 0'
#ports='-p1-65535'
ports='' # use defaults

if [ $# = 0 ] ; then
	echo "No scans specified."
	exit 1
fi

case "$1" in
	real|type)
		if [ "$1" = type ] ; then
			typesearch="${2}."
			versioning=
		else
			typesearch="${2}"
		fi

		# Output is first split into hosts
		nmap $out - -iL - $scan $versioning --allports $ports |
		grep "//${typesearch}/" |
		cut -d' ' -f2- |
		while read hostline ; do
			host=$(echo $hostline | cut -d' ' -f1)

			# And then into ports
			# TODO: simplify this
			echo $hostline |
			#tee /dev/stderr |
			cut -d' ' -f4- |
			tr ' ' '\n' |
			grep "//${typesearch}/" |
			sed 's/\/open\/.*//' |
			while read port ; do
				echo "$host:$port"
			done
		done
		;;
	ports)
		nmap $out - -iL - $scan --allports "$2"
		;;
	*)
		nmap $out - -iL - "$@"
		;;
esac
