#!/bin/bash
# Reverse hexdump anything with xxd

# override with -r
print_hex=false
# override with filename
f=/dev/stdin

for arg ; do
	case "$arg" in
		-r) print_hex=true ;;
		-*) xxd_args+=("$arg") ;;
		*) f=$1; break ;;
	esac
done

if [ ! -r "$f" ] ; then
	echo >&2 "cannot read '$f'."
	exit 1
fi

tr 'A-F' 'a-f' < "$f" |  # convert to lowercase hex
sed 's/[^0-9a-f]//g' |   # remove non-hex
tr -d '\n' |             # remove newlines
fold -w 32 |             # split into lines
sed 's/\(....\)/\1 /g' | # split into groups
while read line ; do     # add line numbers
	[ -z "$n" ] && n=0
	printf '%07x: %s\n' $n "$line"
	let n+=16
done |
xxd -r |
if $print_hex ; then
	xxd "${xxd_args[@]}"
else
	cat
fi
