#!/bin/bash
# A super inefficient way of finding files in rings of depth.
# by Evan Teitelman <teitelmanevan@gmail.com>

for i in {1..100000} ; do
	find . -maxdepth $i -mindepth $(( i - 1 )) "$@"
	next=$(find . -maxdepth $i -mindepth $(( i - 1 )) -type d)

	if [[ -z "$next" ]] ; then
		break
	fi
done
