#!/bin/sh

remote_irc() {
	if command -v weechat &> /dev/null ; then
		irc=weechat
	else
		echo >&2 'no weechat'
		return 1
	fi

	unset DISPLAY

	tmux attach-session -t irc 2> /dev/null ||
	  tmux new-session -n weechat -s irc \; send-keys \
	  "unset HISTFILE; HOME=$tmp $irc && exit" C-m "$@" && exit
}

we_started_ssh=false
cleanup() {
	$we_started_ssh && kill "$SSH_AGENT_PID" 2> /dev/null >&2
}
trap cleanup EXIT

if [[ $1 != rmt ]] ; then
	tmp=$HOME
	remote_irc
else
	if [[ -z "$SSH_AGENT_PID" ]] ; then
		we_started_ssh=true
		eval $(ssh-agent)
		ssh-add
	fi

	tmp=$(ssh irc 'mktemp -d /tmp/weechat.XXXXXX')
	rsync -az "$HOME/.weechat" irc:$tmp
	TERM=xterm-256color ssh -t irc "tmp=$tmp; $(declare -f remote_irc); remote_irc"
fi
