#!/bin/bash
# rot13 strings
# by Evan Teitelman <teitelmanevan@gmail.com>

do_rot13() {
	tr '[a-m][n-z][A-M][N-Z]' '[n-z][a-m][N-Z][A-M]'
}

if [[ $# == 0 ]] ; then
	do_rot13
else
	do_rot13 <<< "$*"
fi
