#!/bin/bash
# Moves files from a source directory to a destination directory and deletes
#  the source directory. If no destination directory is specified, the directory
#  one directory back from the source directory is used.
# by Evan Teitelman <teitelmanevan@gmail.com>

if [[ $# = 0 ]] ; then
	echo >&2 "$(basename "$0") SOURCE [DESTINATION]"
	exit 1
fi

source=$1
dest=${2:-$source/..}

mv "$source"/{*,.??*} -t "$dest" 2> /dev/null
rmdir "$source"
