#!/bin/bash
# Performs common security checks

if [[ $(whoami) != root && "$1" != -f ]] ; then
	echo 2>&1 "You must be root. Use the '-f' flag to override this."
	exit 1
fi

file_checks=false

echo "Users with empty passwords:"
awk -F: '( $2 == "" ) { print $1 }' /etc/shadow

echo
echo "Umask:"
ideal_umask=0077
if [[ $(umask) != $ideal_umask ]] ; then
	echo "umask is '$(umask)' (should be $ideal_umask)."
else
	echo "umask is okay."
fi

echo
echo "Mount flags:"
mount | grep -E "tmpfs" |
while read mount ; do
	for flag in nosuid nodev noexec ; do
		if ! echo "$mount" | grep -q $flag ; then
			echo "'$(echo "$mount" | cut -d' ' -f1-3)' needs $flag flag"
		fi
	done
done

mount | grep -E "\s/home" |
while read mount ; do
	for flag in nosuid nodev ; do
		if ! echo "$mount" | grep -q $flag ; then
			echo "'$(echo "$mount" | cut -d' ' -f1-3)' needs $flag flag"
		fi
	done
done

for file in /etc/shadow /etc/shadow- /etc/passwd /etc/passwd- ; do
	perms=$(stat -c '%a' $file)
	ideal_perms=400
	if [[ $perms != $ideal_perms ]] ; then
		echo "'$file' has permissions '$perms' (should be '$ideal_perms')"
	fi
done

echo
echo "Cron deny:"
grep -v '^#' cron.deny
echo "Cron allow"
grep -v '^#' cron.allow

echo
if [[ -r /etc/sudoers ]] ; then
	echo "Sudo:"
	grep -Ev '^#|^$' /etc/sudoers
	echo
	echo "Sudo NOPASSWD:"
	grep -v '^#' /etc/sudoers | grep 'NOPASSWD'
else
	echo >&2 "Unable to read '/etc/sudoers'"
fi

if $file_checks ; then
	# TODO: files without ?00 permissions

	echo
	echo "Files with '777' permissions:"
	find / -path '/proc/*' -prune -o -type f -path '/tmp/*' -prune -o \( -perm 777 -a ! -type l \) -exec ls -dl {} \;

	echo
	echo "Directories with '777' permissions:"
	find / -path '/proc/*' -prune -o -type d -path '/tmp/*' -prune -o -perm 777 -exec ls -dl {} \;

	echo
	echo "Directories without sticky bit:"
	find / -path '/proc/*' -prune -o -type d \( -perm -0002 -a ! -perm -1000 \) -exec ls -ld {} \;

	echo
	echo "Unowned files:"
	find / -path '/proc/*' -prune -o -type f \( -nouser -o -nogroup \) -exec ls -l {} \;

	echo
	echo "Unowned directories:"
	find / -path '/proc/*' -prune -o -type d \( -nouser -o -nogroup \) -exec ls -ld {} \;

	echo
	echo "SUID/SGID files:"
	find / -path '/proc/*' -prune -o -type f \( -perm -04000 -o -perm -02000 \) -exec ls -l {} \;
fi

# TODO: Check cron file permissions
# TODO: Test for default root passwords
