#!/usr/bin/perl
# Allows you to pass multiple arguments in on a shebang line.
# by Evan Teitelman <teitelmanevan@gmail.com>

use warnings;
use strict;

my ($split, @other_args) = @ARGV;
my $sep = substr $split, 0, 1;

my @args = split /$sep/, $split;
shift @args;
push @args, @other_args;
exec (@args);
