#!/bin/sh

thing=$1
file=$HOME/notes/shitware

if grep -iq "$thing" "$file" ; then
	echo
	grep -ih "$thing" "$file" | nl
	echo
	echo -n 'is it one of these (Yn)? '
	read ans
	case "$ans" in
		n|N) ;;
		*) echo >&2 'not adding.'; exit 1 ;;
	esac
fi
	
echo >&2 "adding '$thing' to shitware list..."
echo "$thing" >> "$file"
