#!/bin/sh

thing=$1
file=$HOME/notes/shitware

if grep -q "$thing" "$file" ; then
	echo
	grep -h "$thing" "$file" | nl
	echo
	echo -n 'is it one of these (yN)? '
	read ans
	case "$ans" in
		y|Y) exit 1 ;;
	esac
fi
	
echo >&2 "adding '$thing' to shitware list..."
echo "$thing" >> "$file"
