#!/bin/bash
# freenode/##linux joke.

case "$1" in
	tunnel)
		ssh -L "$2:$3:$4" "$5"
		;;
	irc)
		(
			echo "NICK $2"
			echo "USER $2 8 * : $2"
			echo "JOIN ${3:-##linux}"
			sed 's/^/PRIVMSG ${3:-##linux} :/'
		) < /dev/tty | telnet ${4:-irc.freenode.net} 6667
		;;
	*)
		ping "$@" |
		awk -F[=\ ] '/me=/{ t=$(NF - 1); f = 120 - log(2 ^ t); c="echo tang | espeak 2>/dev/null -s 200 -p " f; print $0; system(c)  }' |
		sed -u 's/.*bytes from /TANG! /'
		;;
esac
