#!/bin/bash

case "$1" in
	guard)
		def=$2
		if [[ "$def" == *.h ]] ; then
			def=$(echo "$def" | tr [a-z] [A-Z] | sed 's/\./_/g')
		fi
		cat <<-EOF
		#ifndef $def
		#define $def



		#endif /* $def */
		EOF
		;;
	main)
		cat <<-EOF
		int main(int argc, char **argv) {
		}
		EOF
		;;
	stdincl*)
		cat <<-EOF
		#include <stdio.h>
		#include <stdlib.h>
		#include <unistd.h>
		EOF
		;;
	*)
		cat >&2 <<-EOF
		Supported templates:
		  - guard
		  - main
		  - stdincl
		EOF
		exit 1
		;;
esac
