#!/bin/sh
# Test shellcode
# by Evan Teitelman <teitelmanevan@gmail.com>

sc=$1

echo "testing \"$sc\"..."

#cat <<EOF
gcc -x c - <<EOF
#include <sys/mman.h>
#include <string.h>
#include <stdio.h>

char *sc= "$sc";

int main(){
	mprotect(sc, 4096, PROT_EXEC|PROT_READ);
	(*(void(*)())sc)();
	return 42;
}
EOF
