#!/bin/sh
# Test shellcode
# by Evan Teitelman <teitelmanevan@gmail.com>

sc=$1

tcc -run - <<EOF
#include <sys/mman.h>
#include <string.h>
#include <stdio.h>

char sc[]= "$sc";

int main(){
	void * a = mmap(0, 4096, PROT_EXEC |PROT_READ | PROT_WRITE, MAP_ANONYMOUS | MAP_SHARED, -1, 0);
	printf("allocated executable memory at: %p\n", a);
	((void (*)(void)) memcpy(a, sc, sizeof(sc)))();
}
EOF
