#!/bin/bash
# Translate with translate.google.com
# Based one something I found online.
# by Evan Teitelman <teitelmanevan@gmail.com>

default_target=en

if [[ $1 = -h || $1 = --help ]] ; then
	cat <<EOF
$(basename $0) <text> [[<source language>] <target language>]
   If target is missing, uses '$default_target'
   If source is missing, uses 'auto'

An incomplete list of supported languages:
   en - english
   es - spanish
   de - german
   ru - russian
EOF

	exit
fi

if [[ "$1" == - ]] ; then
	text=$(cat)
else
	text=$1
fi

if [[ $3 ]]; then
	source="$2"
	target="$3"
elif [[ $2 ]]; then
	source=auto
	target="$2"
else
	source=auto
	target="$default_target"
fi

result=$(curl -s -i --user-agent "" -d "sl=$source" -d "tl=$target" --data-urlencode "text=$text" https://translate.google.com)
encoding=$(awk '/Content-Type: .* charset=/ {sub(/^.*charset=["'\'']?/,"");
           sub(/[ "'\''].*$/,""); print}' <<< "$result")
#iconv -f $encoding <<<"$result" | awk 'BEGIN {RS="<div"};/<span[^>]* id=["'\'']?result_box["'\'']?/ {sub(/^.*id=["'\'']?result_box["'\'']?(>| [^>]*>)([ \n\t]*<[^>]*>)*/,"");sub(/<.*$/,"");print}' | html2text -utf8
iconv -f $encoding <<< "$result" |  awk 'BEGIN {RS="</div>"};/<span[^>]* id=["'\'']?result_box["'\'']?/' | html2text
