#!/bin/bash

default_target=en

if [[ $1 = -h || $1 = --help ]] ; then
cat <<HERE
$(basename $0) <text> [[<source language>] <target language>]
   If target is missing, uses '$default_target'
   If source is missing, uses 'auto'
HERE

	exit
elif [[ $1 = -l || $1 = --languages ]] ; then
	echo "An incomplete list:
   en - english
   es - spanish
   de - german
   ru - russian"
	exit
fi

if [[ $3 ]]; then
	source="$2"
	target="$3"
elif [[ $2 ]]; then
	source=auto
	target="$2"
else
	source=auto
	target="$default_target"
fi

result=$(curl -s -i --user-agent "" -d "sl=$source" -d "tl=$target" --data-urlencode "text=$1" http://translate.google.com)
encoding=$(awk '/Content-Type: .* charset=/ {sub(/^.*charset=["'\'']?/,"");
sub(/[ "'\''].*$/,""); print}' <<<"$result")
#iconv -f $encoding <<<"$result" | awk 'BEGIN {RS="<div"};/<span[^>]* id=["'\'']?result_box["'\'']?/ {sub(/^.*id=["'\'']?result_box["'\'']?(>| [^>]*>)([ \n\t]*<[^>]*>)*/,"");sub(/<.*$/,"");print}' | html2text -utf8
iconv -f $encoding <<<"$result" |  awk 'BEGIN {RS="</div>"};/<span[^>]* id=["'\'']?result_box["'\'']?/' | html2text
exit
