#!/bin/bash

tag_dir=~/.ctags

mkdir -p "$tag_dir"

# Java
ctags -R --language-force=java -f $tag_dir/java $JAVA_HOME/src
ctags -R --languages=java -a -f $tag_dir/java /usr/lib/gridworld/framework
# Python
ctags -R --languages=python -f $tag_dir/python /usr/lib/python2.*
# C
ctags -R -f $tag_dir/c /usr/include
# C++
ctags -R --languages=c++ -f $tag_dir/cpp /usr/include
