#!/bin/bash
# alsamixer/amixer wrapper
# by Evan Teitelman <teitelmanevan@gmail.com>

if [[ $# == 0 ]] ; then
	# use the gui
	alsamixer
elif [[ $# == 1 ]] ; then
	# set master
	amixer set Master "$1"
else
	# set something else
	amixer set "$@"
fi
