#!/bin/bash
# From privateinternetaccess.com

json=$(curl -s 'http://privateinternetaccess.com/vpninfo/servers?version=24' | head -n1)
python2 <<EOF | column -ts$'\t'
import json
d = json.loads('$json')
print "\n".join([d[k]['name']+'\t'+d[k]['dns'] for k in d.keys() if k != 'info'])
EOF
