#!/bin/bash
# Go to the parent directory until going back becomes impossible
#  or until a .git directory is found in the immediate directory
#  if --nopass is not set and a file named .gitpass exists, pass
#  over that directory and pretend the .git directory does not exist

nopass=false

# Parse arguments
if [[ $1 == '-h' || $1 == '--help' ]]; then
	echo "cdr [-h][--nopass|-n]"
elif [[ $1 == '-n' || $1 == '--nopass' ]]; then
	nopass=true
fi

last_directory=""
while [[ ! -d ".git" || -f ".gitpass" && ! $nopass == true ]]
do
	cd ..
	if [[ $last_directory == $(pwd) ]]; then
		echo Unable to go back any further.
		return 1
	fi
	last_directory="$(pwd)"
done
