#!/bin/bash
# Checks if a command is an alias via git's help command
command="$(git help $1)"
if [[ "$command" =~ " is aliased to " ]] ; then
	# If it is an alias, get the actual command by removing the inclusive
	#  substring between the backticks in "`foo' is aliased to `faa'" and
	#  the last single quote
	command="${command##\`*\`}"
	command="${command%\'}"
	command="${command%%\ *}"
else
	# If not an alias, the command is probably that passed to the script
	command=$1
fi

